# Generated by Django 4.2 on 2023-05-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForumAuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Request', models.CharField(default='None', max_length=100)),
                ('VendorCode', models.CharField(default='None', max_length=100)),
                ('Brand', models.CharField(default='None', max_length=100)),
                ('Product', models.CharField(default='None', max_length=100)),
                ('Applicability', models.CharField(default='None', max_length=100)),
                ('Returns', models.CharField(default='None', max_length=100)),
                ('Delivery', models.CharField(default='None', max_length=100)),
                ('Price', models.CharField(default='None', max_length=100)),
                ('Stock', models.CharField(default='None', max_length=100)),
            ],
        ),
    ]
