# Generated by Django 4.2 on 2023-05-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumauto',
            name='Applicability',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
