# Generated by Django 4.2 on 2023-05-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parser', '0002_alter_forumauto_applicability'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShateM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Request', models.CharField(default='None', max_length=100)),
                ('Brand', models.CharField(default='None', max_length=100)),
                ('Name', models.CharField(default='None', max_length=100)),
                ('Stock', models.CharField(default='None', max_length=100)),
                ('Amount', models.CharField(default='None', max_length=100)),
                ('Rating', models.CharField(default='None', max_length=100)),
                ('Delivery', models.CharField(default='None', max_length=100)),
                ('Price', models.CharField(default='None', max_length=100)),
            ],
        ),
    ]
